### ISSUE TITLE
La aplicación no avisa que requiere conexión a internet y se queda en blanco

### ISSUE THREAD

**Issue by fcoterroba** [TirexSG/Pokedex-APP#1]
# Descripción del error
Actualmente, cuando la aplicación se abre sin conexión a internet, la pantalla permanece en blanco y no se muestra ningún mensaje informando al usuario que se necesita una conexión para que funcione correctamente. 

Esto puede generar confusión, ya que el usuario no recibe ninguna alerta o indicación, y puede pensar que la app está rota o simplemente no responde.

# Pasos para reproducir

1. Abrir la aplicación sin conexión a internet.
2. Observar que la pantalla queda en blanco, sin ningún aviso o mensaje de error.

# Captura de pantalla del error
<img src="https://github.com/user-attachments/assets/ecf18496-d887-4008-8273-c21935bd1584" width="300px" />

# Comportamiento esperado
La aplicación debería mostrar un mensaje claro al usuario indicando que es necesaria una conexión a internet para su correcto funcionamiento.

# Posible solución 
Incluir un mensaje emergente (popup) o un texto visible en la pantalla que avise al usuario sobre la falta de conexión, y ofrezca opciones como "Reintentar" o "Cerrar la aplicación".

**Comment by TirexSG** [comment]
Gracias por avisar del error, ya está solucionado.
